### ISSUE TITLE
Bug na linha 3 da main.c

### ISSUE THREAD

**Issue by DavidGomesh** [DavidGomesh2/ola-mundo#3]
# Erro na linha 3
## Algo nao esta certo aqui
```c
int main(){
    printf("Quem leu eh feio\n");
    return 0;
}
```
![image](https://user-images.githubusercontent.com/53452408/83775390-3df72d80-a65d-11ea-968b-0683da74bb45.png)

**Comment by DavidGomesh2** [comment]
### Como você descobriu isso?
@DavidGomesh2 antes eu fiz uns testes e funcionou de boas.

**Comment by DavidGomesh** [comment]
> ### Como você descobriu isso?
> @DavidGomesh2 antes eu fiz uns testes e funcionou de boas.

### Tu é burro ou tu é feio?
Só ajeita véi, eu que mando nessa parada!
